# You can create this variable in settings -> gitlab -> CI/CD -> Variable
# $DH_USERNAME
# $DH_PASSWORD
image: docker:latest

variables:
  REPOSITORY_URL: vendirn285/homework11
  IMAGE_TAG: latest
services:
- docker:dind
before_script:
  - docker login --username=$DH_USERNAME --password=$DH_PASSWORD
stages:
  - build
  - deploy
build:
  stage: build
  script:
    - echo "Building image..."
    - docker build 
      -t homework11:latest 
      --build-arg PORT=$PORT 
      --no-cache .
    - echo "Tagging image..."
    - docker tag homework11:latest $REPOSITORY_URL:latest
    - echo "Pushing image..."
    - docker push $REPOSITORY_URL:latest
  only:
    - master
deploy:
  stage: deploy
  script:
    - docker stop homework11 || true && docker rm homework11 || true
    - docker container run -dt -p $PORT:$PORT --name homework11 $REPOSITORY_URL:latest
    - docker image prune -f
  only:
    - master