version: '3'

networks:
  app-tier:
    driver: bridge

services:
  homework11:
    build: .
    networks:
      - app-tier
    ports:
      - "3000:3000"
    depends_on:
      - dbpgsql
    volumes:
      - ./homework11:/app/src/homework11
  dbpgsql:
    image: postgres:16.1
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - app-tier